apiVersion: apps/v1
kind: Deployment
metadata:
  name: SERVICE_NAME
  labels:
    app: SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SERVICE_NAME
    template:
      metadata:
        labels:
          app: SERVICE_NAME
      spec:
        container:
          - name: SERVICE_NAME
            image: DOCKER_REPO/SERVICE_NAME:IMAGE_TAG
            ports:
              - name: SERVICE_NAME-port
                port: SERVICE_PORT
